services:
  db-test:
    build:
      context: ./server/src/db/
      dockerfile: Dockerfile.test
    restart: always
    container_name: kiruna_postgis_test
    env_file:
      - .env.test
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
