services:
  db:
    image: postgis/postgis:17-3.5 # PostGIS with PostgreSQL 17
    restart: always
    container_name: postgis
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - kiruna_postgis_data:/var/lib/postgresql/data # Persistent storage for db data

  db_gui:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80" # Exposing pgAdmin on port 5050
    depends_on:
      - db
    volumes:
      - kiruna_pgadmin_data:/var/lib/pgadmin # Persist pgAdmin data

volumes:
  kiruna_postgis_data: # Persistent named volume for db data
  kiruna_pgadmin_data: # Persistent named volume for pgAdmin
