services:
  db:
    build:
      context: ./server/src/db/
      dockerfile: Dockerfile.dev
    restart: always
    container_name: kiruna_postgis
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - kiruna_postgis_data:/var/lib/postgresql/data # Persistent storage for db data

  db_gui:
    image: dpage/pgadmin4:latest
    container_name: kiruna_pgadmin
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80" # Exposing pgAdmin on port 5050
    volumes:
      - kiruna_pgadmin_data:/var/lib/pgadmin # Persist pgAdmin data

volumes:
  kiruna_postgis_data: # Persistent named volume for db data
  kiruna_pgadmin_data: # Persistent named volume for pgAdmin
